export const ADD_MEDICINE = "ADD_MEDICINE";
export const SHOW_SCHEDULE = "SHOW_SCHEDULE";
export const SET_NEW_MEDICINE = "SET_NEW_MEDICINE";
export const ADD_NEW_MEDICINE = "ADD_NEW_MEDICINE";
export const UPDATE_SCHEDULE_CHECKBOX = "UPDATE_SCHEDULE_CHECKBOX ";